/*==============================================================*/
/* POBLAMIENTO DE PERFILES/ROLES USUARIOS(SPRING SECURITY)      */
/*==============================================================*/

INSERT INTO PERFIL(ID_PERFIL,NOMBRE,HABILITADO) VALUES(1,'ADMINISTRADOR',true);
INSERT INTO PERFIL(ID_PERFIL,NOMBRE,HABILITADO) VALUES(2,'EMPRESA',true);
INSERT INTO PERFIL(ID_PERFIL,NOMBRE,HABILITADO) VALUES(3,'PROVEEDOR',true);
INSERT INTO PERFIL(ID_PERFIL,NOMBRE,HABILITADO) VALUES(4,'COLABORADOR',true);
