/*==============================================================*/
/* POBLAMIENTO DE PERFILES/ROLES USUARIOS(SPRING SECURITY)      */
/*==============================================================*/

INSERT INTO PERFIL(ID_PERFIL,NOMBRE,HABILITADO) VALUES(1,'ROLE_ADMINISTRADOR',true);
INSERT INTO PERFIL(ID_PERFIL,NOMBRE,HABILITADO) VALUES(2,'ROLE_EMPRESA',true);
INSERT INTO PERFIL(ID_PERFIL,NOMBRE,HABILITADO) VALUES(3,'ROLE_PROVEEDOR',true);
INSERT INTO PERFIL(ID_PERFIL,NOMBRE,HABILITADO) VALUES(4,'ROLE_COLABORADOR',true);
