/* 
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 * Author:  Marcos
 * Created: 23-abr-2017
 */

-- CATEGORIAS
INSERT INTO CATEGORIA (ID_CATEGORIA_PADRE, NOMBRE, DESCRIPCION, ID_CATEGORIA) VALUES (-1, 'Productos','Productos',1);
INSERT INTO CATEGORIA (ID_CATEGORIA_PADRE, NOMBRE, DESCRIPCION, ID_CATEGORIA) VALUES (-1, 'Viajes','Viajes',2);
INSERT INTO CATEGORIA (ID_CATEGORIA_PADRE, NOMBRE, DESCRIPCION, ID_CATEGORIA) VALUES (-1, 'Belleza','Belleza',3);
INSERT INTO CATEGORIA (ID_CATEGORIA_PADRE, NOMBRE, DESCRIPCION, ID_CATEGORIA) VALUES (-1, 'Salud y Bienestar','Salud y Bienestar',4);
INSERT INTO CATEGORIA (ID_CATEGORIA_PADRE, NOMBRE, DESCRIPCION, ID_CATEGORIA) VALUES (-1, 'Gastronomía','Gastronomía',5);
INSERT INTO CATEGORIA (ID_CATEGORIA_PADRE, NOMBRE, DESCRIPCION, ID_CATEGORIA) VALUES (-1, 'Servicios','Servicios',6);
INSERT INTO CATEGORIA (ID_CATEGORIA_PADRE, NOMBRE, DESCRIPCION, ID_CATEGORIA) VALUES (-1, 'Tickets','Tickets',7);
INSERT INTO CATEGORIA (ID_CATEGORIA_PADRE, NOMBRE, DESCRIPCION, ID_CATEGORIA) VALUES (-1, 'Tiempo Libre','Tiempo Libre',8);

-- SUB CATEGORIAS
INSERT INTO CATEGORIA (ID_CATEGORIA_PADRE, NOMBRE, DESCRIPCION, ID_CATEGORIA) VALUES (1, 'Infantil y juguetes','Infantil y juguetes',109);
INSERT INTO CATEGORIA (ID_CATEGORIA_PADRE, NOMBRE, DESCRIPCION, ID_CATEGORIA) VALUES (1, 'Lentes de sol y óptica','Lentes de sol y óptica',110);
INSERT INTO CATEGORIA (ID_CATEGORIA_PADRE, NOMBRE, DESCRIPCION, ID_CATEGORIA) VALUES (1, 'libros, música y oscio','libros, música y oscio',111);
INSERT INTO CATEGORIA (ID_CATEGORIA_PADRE, NOMBRE, DESCRIPCION, ID_CATEGORIA) VALUES (1, 'Limpieza','Limpieza',112);
INSERT INTO CATEGORIA (ID_CATEGORIA_PADRE, NOMBRE, DESCRIPCION, ID_CATEGORIA) VALUES (1, 'Maletería y Accesorios de Viaje','Maletería y Accesorios de Viaje',113);
INSERT INTO CATEGORIA (ID_CATEGORIA_PADRE, NOMBRE, DESCRIPCION, ID_CATEGORIA) VALUES (1, 'Mascotas','Mascotas',114);
INSERT INTO CATEGORIA (ID_CATEGORIA_PADRE, NOMBRE, DESCRIPCION, ID_CATEGORIA) VALUES (1, 'Salud y Farmacia','Salud y Farmacia',115);
INSERT INTO CATEGORIA (ID_CATEGORIA_PADRE, NOMBRE, DESCRIPCION, ID_CATEGORIA) VALUES (1, 'Tecnología','Tecnología',116);
INSERT INTO CATEGORIA (ID_CATEGORIA_PADRE, NOMBRE, DESCRIPCION, ID_CATEGORIA) VALUES (1, 'Vestuario y Calzado','Vestuario y Calzado',117);
INSERT INTO CATEGORIA (ID_CATEGORIA_PADRE, NOMBRE, DESCRIPCION, ID_CATEGORIA) VALUES (1, 'Vinos, licores y Cervezas','Vinos, licores y Cervezas',118);
INSERT INTO CATEGORIA (ID_CATEGORIA_PADRE, NOMBRE, DESCRIPCION, ID_CATEGORIA) VALUES (1, 'Otro','Otro',119);
INSERT INTO CATEGORIA (ID_CATEGORIA_PADRE, NOMBRE, DESCRIPCION, ID_CATEGORIA) VALUES (2, 'Chile Norte','Chile Norte',201);
INSERT INTO CATEGORIA (ID_CATEGORIA_PADRE, NOMBRE, DESCRIPCION, ID_CATEGORIA) VALUES (2, 'Chile Centro','Chile Centro',202);
INSERT INTO CATEGORIA (ID_CATEGORIA_PADRE, NOMBRE, DESCRIPCION, ID_CATEGORIA) VALUES (2, 'Chile Sur','Chile Sur',203);
INSERT INTO CATEGORIA (ID_CATEGORIA_PADRE, NOMBRE, DESCRIPCION, ID_CATEGORIA) VALUES (2, 'Sudamerica','Sudamerica',204);
INSERT INTO CATEGORIA (ID_CATEGORIA_PADRE, NOMBRE, DESCRIPCION, ID_CATEGORIA) VALUES (2, 'Caribe','Caribe',205);
INSERT INTO CATEGORIA (ID_CATEGORIA_PADRE, NOMBRE, DESCRIPCION, ID_CATEGORIA) VALUES (2, 'Norte America','Norte America',206);
INSERT INTO CATEGORIA (ID_CATEGORIA_PADRE, NOMBRE, DESCRIPCION, ID_CATEGORIA) VALUES (2, 'Europa','Europa',207);
INSERT INTO CATEGORIA (ID_CATEGORIA_PADRE, NOMBRE, DESCRIPCION, ID_CATEGORIA) VALUES (2, 'Asía','Asía',208);
INSERT INTO CATEGORIA (ID_CATEGORIA_PADRE, NOMBRE, DESCRIPCION, ID_CATEGORIA) VALUES (2, 'África','África',209);
INSERT INTO CATEGORIA (ID_CATEGORIA_PADRE, NOMBRE, DESCRIPCION, ID_CATEGORIA) VALUES (2, 'Oceanía','Oceanía',210);
INSERT INTO CATEGORIA (ID_CATEGORIA_PADRE, NOMBRE, DESCRIPCION, ID_CATEGORIA) VALUES (2, 'Otro','Otro',211);
INSERT INTO CATEGORIA (ID_CATEGORIA_PADRE, NOMBRE, DESCRIPCION, ID_CATEGORIA) VALUES (3, 'Tratamiento Reductor','Tratamiento Reductor',301);
INSERT INTO CATEGORIA (ID_CATEGORIA_PADRE, NOMBRE, DESCRIPCION, ID_CATEGORIA) VALUES (3, 'Peluquería','Peluquería',302);
INSERT INTO CATEGORIA (ID_CATEGORIA_PADRE, NOMBRE, DESCRIPCION, ID_CATEGORIA) VALUES (3, 'Depilación','Depilación',303);
INSERT INTO CATEGORIA (ID_CATEGORIA_PADRE, NOMBRE, DESCRIPCION, ID_CATEGORIA) VALUES (3, 'Limpieza Facial','Limpieza Facial',304);
INSERT INTO CATEGORIA (ID_CATEGORIA_PADRE, NOMBRE, DESCRIPCION, ID_CATEGORIA) VALUES (3, 'Cuidado Dental','Cuidado Dental',305);
INSERT INTO CATEGORIA (ID_CATEGORIA_PADRE, NOMBRE, DESCRIPCION, ID_CATEGORIA) VALUES (3, 'Cuidado de Uñas','Cuidado de Uñas',306);
INSERT INTO CATEGORIA (ID_CATEGORIA_PADRE, NOMBRE, DESCRIPCION, ID_CATEGORIA) VALUES (3, 'Cuidado de la piel','Cuidado de la piel',307);
INSERT INTO CATEGORIA (ID_CATEGORIA_PADRE, NOMBRE, DESCRIPCION, ID_CATEGORIA) VALUES (3, 'Cuidado de pies','Cuidado de pies',308);
INSERT INTO CATEGORIA (ID_CATEGORIA_PADRE, NOMBRE, DESCRIPCION, ID_CATEGORIA) VALUES (3, 'Otro','Otro',309);
INSERT INTO CATEGORIA (ID_CATEGORIA_PADRE, NOMBRE, DESCRIPCION, ID_CATEGORIA) VALUES (4, 'Masajes','Masajes',401);
INSERT INTO CATEGORIA (ID_CATEGORIA_PADRE, NOMBRE, DESCRIPCION, ID_CATEGORIA) VALUES (4, 'Spa','Spa',402);
INSERT INTO CATEGORIA (ID_CATEGORIA_PADRE, NOMBRE, DESCRIPCION, ID_CATEGORIA) VALUES (4, 'Odontología','Odontología',403);
INSERT INTO CATEGORIA (ID_CATEGORIA_PADRE, NOMBRE, DESCRIPCION, ID_CATEGORIA) VALUES (4, 'Medicina General','Medicina General',404);
INSERT INTO CATEGORIA (ID_CATEGORIA_PADRE, NOMBRE, DESCRIPCION, ID_CATEGORIA) VALUES (4, 'Cirugía Estética','Cirugía Estética',405);
INSERT INTO CATEGORIA (ID_CATEGORIA_PADRE, NOMBRE, DESCRIPCION, ID_CATEGORIA) VALUES (4, 'Medicina Alternativa','Medicina Alternativa',406);
INSERT INTO CATEGORIA (ID_CATEGORIA_PADRE, NOMBRE, DESCRIPCION, ID_CATEGORIA) VALUES (4, 'Otros','Otros',407);
INSERT INTO CATEGORIA (ID_CATEGORIA_PADRE, NOMBRE, DESCRIPCION, ID_CATEGORIA) VALUES (5, 'Restaurante','Restaurante',501);
INSERT INTO CATEGORIA (ID_CATEGORIA_PADRE, NOMBRE, DESCRIPCION, ID_CATEGORIA) VALUES (5, 'Comida Rápida','Comida Rápida',502);
INSERT INTO CATEGORIA (ID_CATEGORIA_PADRE, NOMBRE, DESCRIPCION, ID_CATEGORIA) VALUES (5, 'Heladería','Heladería',503);
INSERT INTO CATEGORIA (ID_CATEGORIA_PADRE, NOMBRE, DESCRIPCION, ID_CATEGORIA) VALUES (5, 'Bar','Bar',504);
INSERT INTO CATEGORIA (ID_CATEGORIA_PADRE, NOMBRE, DESCRIPCION, ID_CATEGORIA) VALUES (5, 'Tenedor Libre','Tenedor Libre',505);
INSERT INTO CATEGORIA (ID_CATEGORIA_PADRE, NOMBRE, DESCRIPCION, ID_CATEGORIA) VALUES (5, 'Pastelería','Pastelería',506);
INSERT INTO CATEGORIA (ID_CATEGORIA_PADRE, NOMBRE, DESCRIPCION, ID_CATEGORIA) VALUES (5, 'Otro','Otro',507);
INSERT INTO CATEGORIA (ID_CATEGORIA_PADRE, NOMBRE, DESCRIPCION, ID_CATEGORIA) VALUES (6, 'Cursos','Cursos',601);
INSERT INTO CATEGORIA (ID_CATEGORIA_PADRE, NOMBRE, DESCRIPCION, ID_CATEGORIA) VALUES (6, 'Productos Personalizados','Productos Personalizados',602);
INSERT INTO CATEGORIA (ID_CATEGORIA_PADRE, NOMBRE, DESCRIPCION, ID_CATEGORIA) VALUES (6, 'Automotriz','Automotriz',603);
INSERT INTO CATEGORIA (ID_CATEGORIA_PADRE, NOMBRE, DESCRIPCION, ID_CATEGORIA) VALUES (6, 'Reparaciones','Reparaciones',604);
INSERT INTO CATEGORIA (ID_CATEGORIA_PADRE, NOMBRE, DESCRIPCION, ID_CATEGORIA) VALUES (6, 'Fotografía','Fotografía',605);
INSERT INTO CATEGORIA (ID_CATEGORIA_PADRE, NOMBRE, DESCRIPCION, ID_CATEGORIA) VALUES (6, 'Despacho','Despacho',606);
INSERT INTO CATEGORIA (ID_CATEGORIA_PADRE, NOMBRE, DESCRIPCION, ID_CATEGORIA) VALUES (6, 'Mascotas','Mascotas',607);
INSERT INTO CATEGORIA (ID_CATEGORIA_PADRE, NOMBRE, DESCRIPCION, ID_CATEGORIA) VALUES (6, 'De Lujo','De Lujo',608);
INSERT INTO CATEGORIA (ID_CATEGORIA_PADRE, NOMBRE, DESCRIPCION, ID_CATEGORIA) VALUES (6, 'Asesoría','Asesoría',609);
INSERT INTO CATEGORIA (ID_CATEGORIA_PADRE, NOMBRE, DESCRIPCION, ID_CATEGORIA) VALUES (6, 'Alquileres','Alquileres',610);
INSERT INTO CATEGORIA (ID_CATEGORIA_PADRE, NOMBRE, DESCRIPCION, ID_CATEGORIA) VALUES (6, 'Tatuajes y Piercings','Tatuajes y Piercings',611);
INSERT INTO CATEGORIA (ID_CATEGORIA_PADRE, NOMBRE, DESCRIPCION, ID_CATEGORIA) VALUES (6, 'Limpieza','Limpieza',612);
INSERT INTO CATEGORIA (ID_CATEGORIA_PADRE, NOMBRE, DESCRIPCION, ID_CATEGORIA) VALUES (6, 'Suscripciones','Suscripciones',613);
INSERT INTO CATEGORIA (ID_CATEGORIA_PADRE, NOMBRE, DESCRIPCION, ID_CATEGORIA) VALUES (6, 'Otro','Otro',614);
INSERT INTO CATEGORIA (ID_CATEGORIA_PADRE, NOMBRE, DESCRIPCION, ID_CATEGORIA) VALUES (7, 'Cine','Cine',701);
INSERT INTO CATEGORIA (ID_CATEGORIA_PADRE, NOMBRE, DESCRIPCION, ID_CATEGORIA) VALUES (7, 'Cultural','Cultural',702);
INSERT INTO CATEGORIA (ID_CATEGORIA_PADRE, NOMBRE, DESCRIPCION, ID_CATEGORIA) VALUES (7, 'Parques','Parques',703);
INSERT INTO CATEGORIA (ID_CATEGORIA_PADRE, NOMBRE, DESCRIPCION, ID_CATEGORIA) VALUES (7, 'Fiestas','Fiestas',704);
INSERT INTO CATEGORIA (ID_CATEGORIA_PADRE, NOMBRE, DESCRIPCION, ID_CATEGORIA) VALUES (7, 'Deportes','Deportes',705);
INSERT INTO CATEGORIA (ID_CATEGORIA_PADRE, NOMBRE, DESCRIPCION, ID_CATEGORIA) VALUES (7, 'Conciertos','Conciertos',706);
INSERT INTO CATEGORIA (ID_CATEGORIA_PADRE, NOMBRE, DESCRIPCION, ID_CATEGORIA) VALUES (7, 'Otro','Otro',707);
INSERT INTO CATEGORIA (ID_CATEGORIA_PADRE, NOMBRE, DESCRIPCION, ID_CATEGORIA) VALUES (8, 'Ejercicio','Ejercicio',801);
INSERT INTO CATEGORIA (ID_CATEGORIA_PADRE, NOMBRE, DESCRIPCION, ID_CATEGORIA) VALUES (8, 'Vuelos','Vuelos',802);
INSERT INTO CATEGORIA (ID_CATEGORIA_PADRE, NOMBRE, DESCRIPCION, ID_CATEGORIA) VALUES (8, 'Deportes del Ocio','Deportes del Ocio',803);
INSERT INTO CATEGORIA (ID_CATEGORIA_PADRE, NOMBRE, DESCRIPCION, ID_CATEGORIA) VALUES (8, 'Tiro','Tiro',804);
INSERT INTO CATEGORIA (ID_CATEGORIA_PADRE, NOMBRE, DESCRIPCION, ID_CATEGORIA) VALUES (8, 'Baile','Baile',805);
INSERT INTO CATEGORIA (ID_CATEGORIA_PADRE, NOMBRE, DESCRIPCION, ID_CATEGORIA) VALUES (8, 'Motores','Motores',806);
INSERT INTO CATEGORIA (ID_CATEGORIA_PADRE, NOMBRE, DESCRIPCION, ID_CATEGORIA) VALUES (8, 'Experiencias','Experiencias',807);
INSERT INTO CATEGORIA (ID_CATEGORIA_PADRE, NOMBRE, DESCRIPCION, ID_CATEGORIA) VALUES (8, 'Otro','Otro',808);